
data_dir: /aigc_cfs_2/weimao/non-smalfit/dataset/SK_Dolphin
out_dir: /aigc_cfs_2/weimao/non-smalfit/output/SK_Dolphin
prior_dir: ''

point_feature_model_config:
  model_dir: /aigc_cfs_2/weimao/non-smalfit/output/SK_Dolphin/contrast_rot_aug_PointTransformerSeg38/2024-07-26_15-17-39
  model: PointTransformerSeg38
  npoints: 4096

lrs: [2.e-2, 1.e-2, 1.e-1]
maxiters: [200, 200, 200, 200]
chamfer_weights: [1.0, 1.0, 1.0]
pose_prior_weights: [0, 0.001, 0.005]
scale_LR_weights: [0, 10.0, 10.0]
scale_parts_weights: [0, 0.5, 0.5]