
template_dir: /aigc_cfs_2/weimao/non-smalfit/dataset/SK_Dolphin

lrs: [2.e-2, 1.e-2, 1.e-1]
maxiters: [200, 200, 200, 200]
chamfer_weights: [1.0, 1.0, 1.0]
pose_prior_weights: [0, 0.001, 0.005]
scale_LR_weights: [0, 10.0, 10.0]
scale_parts_weights: [0, 0.5, 0.5]