
data_dir: /aigc_cfs_2/weimao/non-smalfit/dataset/SK_Elephant
out_dir: /aigc_cfs_2/weimao/non-smalfit/output/SK_Elephant

model_conf:
  model_name: VAE
  num_layer: 6
  feat_dim: 256

training:
  lr: 1.e-3
  batch_size: 4096
  num_epoch: 200
  weight_prior: 0.1